### ISSUE TITLE
separate repo?

### ISSUE THREAD

**Issue by dnelson86** [cbyrohl/scida-cookbooks#1]
Is this repo all the 'cookbooks' that currently exist for scida?

I would suggest to merge, i.e. just to put a 'cookbook' directory of notebooks into the main scida repository, and delete this repo.

Is there a reason not to?

**Comment by cbyrohl** [comment]
As some notebooks can be relatively large in size due to embedded plots, I initially thought it would be best to keep them separate to not the bloat the repository.

**Comment by dnelson86** [comment]
I think discoverability, easy of use, and user friendliness are probably much more important.

With small plot sizes, we should be able to keep the notebooks to a reasonable size?

**Comment by cbyrohl** [comment]
sure thing, fixed with cbyrohl/scida#153, thanks
